services:
  event-reminder-client:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    networks:
      - event-reminder-network
    environment:
      - NODE_ENV=production
      - FE_DEVELOPMENT=${FE_DEVELOPMENT}
#    depends_on:
#      - db
#    restart_policy:
#      condition: on-failure
#  db:
#    image: postgres
#    environment:
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=postgres
#    volumes:
#      - db-data:/var/lib/postgresql/data
#    restart_policy:
#      condition: on-failure
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - "4180:4180"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - event-reminder-client
    networks:
      - event-reminder-network
    environment:
      - OAUTH2_PROXY_PROVIDER=github
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:4180/oauth2/callback
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_UPSTREAMS=${SVELTEKIT_SERVER_URL}
      - OAUTH2_PROXY_HTTP_ADDRESS=http://0.0.0.0:4180
      - OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=true
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_WHITELIST_DOMAINS=${SVELTEKIT_SERVER_DOMAIN}
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true

volumes:
  db-data:

networks:
  event-reminder-network:
    driver: bridge